spec: v1.0
desc: Catalog for working with Akromio registries.

dataset:
  - const: src
    desc: Dir where the source templates are.
    value: $(__dir)/_$(__catalogName)
    tags: [hidden]
  
  - const: dst
    desc: Local directory where to save the files.
    value: $(workDir)
  
  - const: createRegistryQ
    desc: Questions for the creation of a new registry.
    tags: [hidden, questions]
    value:
      - input: registryName
      - input: registryDesc
      - input: registryDir
        title: "Registry dir (local: .akromio; git: registry)"
  
  - const: createCatalogQ
    desc: Questions for the creation of a new catalog.
    tags: [hidden, questions]
    value:
      - input: catalogName
      - input: catalogDesc
      - input: registryDir
        title: "Registry dir (local: .akromio; git: registry)"
      
defaultJobName: create-registry
jobs:
  - macro: create-registry
    title: Create registry
    ini:
      - quiet: $answers = inquire $(createRegistryQ) $(answers)
    dataset: [item, content]
    steps:
      - fs.createDir $(dst)/$(answers.registryDir)/$(krm.jobs.catalogs.path)
      - cr.copy $(src)/_gitignore $(dst)/.gitignore
      - quiet: $item = cr.getItem $(src)/README.md.hbs
      - quiet: $content = hbs.render $(item.value) $(answers)
      - file.write $(content) $(dst)/README.md

  - macro: create-catalog
    title: Create catalog
    ini:
      - quiet: $answers = inquire $(createCatalogQ) $(answers)
    dataset: [item, content]
    steps:
      - fs.createDir $(dst)/$(answers.registryDir)/$(krm.jobs.catalogs.path)/_$(answers.catalogName)
      - quiet: $item = cr.getItem $(src)/catalog/catalog.yaml.hbs
      - quiet: $content = hbs.render $(item.value) $(answers)
      - file.write $(content) $(dst)/$(answers.registryDir)/$(krm.jobs.catalogs.path)/$(answers.catalogName).yaml

  - macro: bug-report-issue-template
    title: Create an issue template for bug reports
    steps:
      - fs.createDir $(dst)/.github/ISSUE_TEMPLATE
      - cr.copy $(src)/issue-templates/bug-report.yaml $(dst)/.github/ISSUE_TEMPLATE/bug-report.yaml
  
  - macro: feature-request-issue-template
    title: Create an issue template for feature requests
    steps:
      - fs.createDir $(dst)/.github/ISSUE_TEMPLATE
      - cr.copy $(src)/issue-templates/feature-request.yaml $(dst)/.github/ISSUE_TEMPLATE/feature-request.yaml
